### ISSUE TITLE
No NeoForge loader tag works for both CurseForge and Modrinth

### ISSUE THREAD

**Issue by Snownee** [shedaniel/unified-publishing#4]
I tried with `gameLoaders = ["neoforge"]` and `gameLoaders = ["NeoForge"]`, both of which had problems.

**Comment by shedaniel** [comment]
Since CurseGradle seems to have died (closed source), I will need to find an alternative to that first sadly. This is more changes than I anticipated, I will look into fixing this since I need this too.

**Comment by shedaniel** [comment]
This is now fixed
